[package]
name = "interp-pl"
version = "0.1.0"
authors = ["Arun Drelich <arun@instabase.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
